#!/bin/sh
# Busybox udhcpc6 service discovery script.
#
#  Based on udhcp4_sd
#
#  SPDX-License-Identifier:     GPL-2.0

PROG="DHCPv6"

case $1 in
    bound|renew)

        # Print responses usable by onie, prefixed with "onie_disco"
        # Translate '=' into '@', e.g. name=val => name@@val
        # Separate name@val pairs with '##'
        # Busybox udhcpc6 exports the DHCPv6 Boot File URL (option 59)
        # as 'bootfile'; the generic pipeline below maps it to
        # onie_disco_bootfile like every other option variable.
        onie_parms=$(printenv | sed -e '/.*=$/d' -e '/^[A-Z_]/d' -e '/^onie.*/d' -e 's/=/@@/' -e 's/$/#/' -e 's/^/onie_disco_/' | tr '
' '#')

        echo "ONIE_PARMS:$onie_parms"

        ;;

    *)
        ;;
esac
